### ISSUE TITLE
Migrate DEX front-end changes from mugrebot

### ISSUE THREAD

**Issue by steve0xp** [squirtleDevs/scaffold-eth#7]
- [ ] Migrate mugrebot changes from old branch to this branch.
- See what doing a PR from the old repo to the new repo looks like. From there, take the changes you want. You might be better off just editing the files locally and making a new push, but making sure to credit mugrebot. 
- [ ] Test to make sure front end works with contracts, and without (at least loads)
- Run a localhost test to see how it all functions now with the migrated code changes.
- [ ] Update the README.md with these aspects, and check off what front-end issues this all resolves.
- Change screenshots if needed
- Add text outlining event updates and whatnot

**Comment by steve0xp** [comment]
Went through first task, and found that it was not working when I manually made the changes to the final challenge branch. I think it may be due to some syntax fine-tuning, specifically with event naming. I am going to do the following:
- clone the old repo with mugrebot working event emission
- confirm that it works out of box.
- create a new branch off of the sp-ch-4-DEX branch, and rename it challenge-3-SinglePoolDEX
- migrate the README.md, template solidity files, and anything else necessary from my challenge-3-simpleDEX branch.
- Make sure it still works out of the box.
- Change event names and see if it still works, one by one.
- Finalize.

Lesson to all those creating challenges to ensure they are working on the same branches!

**Comment by steve0xp** [comment]
Out of the box, I noticed that there were some issues with the front end from mugrebot last commit:
- Events emitted seem to work as hoped, as well as UI of liquidity in top right of UI.
    - After carrying out some ethToToken and tokenToEth transactions, the withdraw() and deposit() functions do not work as they should it appears. The withdraw() may be working okay, but the deposit() does not seem to actually "mint" liquidity as seen within the events UI: 
    
![image](https://user-images.githubusercontent.com/33653442/152705131-1e28c5a4-b038-46e4-8f85-fc6a3d6b0858.png)

- Going to change price function too and any other implementation logic to see if that works too, as per my latest contract beforehand. mugrebot seems to have an older version of the smart contract logic (aside from events).

**Comment by steve0xp** [comment]
@mugrebot I think the issue with the deposit function at the moment, and possibly within the withdraw function, has to do with the math that is dictating the price function, resulting in impermanent loss. Perhaps that is causing certain parts of the math to zero out, resulting in situations where we get deposited events emitted but 0 liquidity minted as seen in the last tx in this event log:

![image](https://user-images.githubusercontent.com/33653442/152705849-69fd8014-68c5-4de9-a4c8-c91c49b93bb0.png)

We will need to explore this or raise it to the group to see what they think.

**Comment by steve0xp** [comment]
The above issue still stands, but the repo has been updated to emit the events. All functions work at the start but for some reason zeroing out happens for newly minted liquidity (when `deposit()`) is called, and also there are issues with `withdraw()` and the front end it appears too after certain sequences of transactions are carried out. 

The front ends as a whole works at the start but there seems to be some edge cases that make the front end not work. Again, I think has to do with some mathematical setup, and of course there could be an issue with how we are displaying it! Any help or insight is appreciated!

**Comment by dec3ntraliz3d** [comment]
> The above issue still stands, but the repo has been updated to emit the events. All functions work at the start but for some reason zeroing out happens for newly minted liquidity (when `deposit()`) is called, and also there are issues with `withdraw()` and the front end it appears too after certain sequences of transactions are carried out.
> 
> The front ends as a whole works at the start but there seems to be some edge cases that make the front end not work. Again, I think has to do with some mathematical setup, and of course there could be an issue with how we are displaying it! Any help or insight is appreciated!

I had to make slight changes to withdraw() function . 

From the medium post :

```
function withdraw(uint256 amount) public returns (uint256, uint256) {
  uint256 token_reserve = token.balanceOf(address(this));
  uint256 eth_amount = amount.mul(address(this).balance) / totalLiquidity;
  uint256 token_amount = amount.mul(token_reserve) / totalLiquidity;
  liquidity[msg.sender] = liquidity[msg.sender].sub(eth_amount);
  totalLiquidity = totalLiquidity.sub(eth_amount);
  msg.sender.transfer(eth_amount);
  require(token.transfer(msg.sender, token_amount));
  return (eth_amount, token_amount);
}
```


My changes:
```
function withdraw(uint256 _amount) public returns (uint256, uint256) {
        uint256 tokenReserve = token.balanceOf(address(this));
        uint256 ethAmount = _amount.mul(address(this).balance) / totalLiquidity;
        uint256 tokenAmount = _amount.mul(tokenReserve) / totalLiquidity;
        
// I made changes to below two lines. Instead of eth_amount I used liquidity amount requested by sender.
        liquidity[msg.sender] = liquidity[msg.sender].sub(_amount);
        totalLiquidity = totalLiquidity.sub(_amount);
      
  (bool sent, ) = payable(msg.sender).call{value: ethAmount}("");
        require(sent, "Eth transfer failed");
        require(token.transfer(msg.sender, tokenAmount));
        return (ethAmount, tokenAmount);
    }
```

**Comment by steve0xp** [comment]
It turns out that the issue was misplaced parentheses this whole time. SafeMath within solidity is not commutative. The below screenshot shows the incorrect way to do the function with respect to parantheses placement, whereas the second screenshot shows the correct format (which is in the solutions code now).

Incorrect:
![tg_image_3341678022](https://user-images.githubusercontent.com/33653442/153058705-bfcf50a5-8251-4f42-b963-53abb45e053d.jpeg)

Correct:
![tg_image_3612463226](https://user-images.githubusercontent.com/33653442/153058757-346ec0d8-68f4-4218-81ca-3067f19e85f1.jpeg)
